const TYPES = {
  CHEERS_RECEIVED: "CHEERS_RECEIVED",
  CHEERS_GIVEN: "CHEERS_GIVEN"
};

const DURATION = {
  CURRENT_WEEK: "CURRENT_WEEK",
  PAST_WEEK: "PAST_WEEK",
  PAST_2_WEEKS: "PAST_2_WEEKS",
  PAST_3_WEEKS: "PAST_3_WEEKS",
  LAST_MONTH: "LAST_MONTH",
  LAST_2_MONTHS: "LAST_2_MONTHS",
  LAST_3_MONTHS: "LAST_3_MONTHS",
  LAST_6_MONTHS: "LAST_6_MONTHS",
  ALL_TIME: "ALL_TIME"
};

module.exports = { TYPES, DURATION };
